create table ADM_OPER_GROUP_USER(
	IDX_ADM_OPER_GROUP bigint not null,
	IDX_ADM_OPERATOR bigint not null,
	CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

	constraint ADM_OPER_GROUP_USER_UNIQUE_0 unique(IDX_ADM_OPER_GROUP, IDX_ADM_OPERATOR)
);

insert into ADM_OPER_GROUP_USER (IDX_ADM_OPER_GROUP, IDX_ADM_OPERATOR) values (1, 2);
