create table SYS_MENU(
	DB_IDX bigint not null auto_increment primary key,
	MENU_NAME VARCHAR(20) not null,
	ACTION_CODE VARCHAR(10) NOT NULL,
	UPDATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

insert into SYS_MENU (MENU_NAME, ACTION_CODE) values ('TEST_MENU_1', 'C,R,U,D');
insert into SYS_MENU (MENU_NAME, ACTION_CODE) values ('TEST_MENU_2', 'C,R,U,D');
