create table ADM_GROUP_PERMISSION(
	IDX_ADM_OPER_GROUP bigint not null,
	IDX_ADM_SYS_MENU bigint not null,
	PERMISSION VARCHAR(10) NOT NULL,
	UPDATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    constraint ADM_GROUP_PERMISSION_UNIQUE_0 unique(IDX_ADM_OPER_GROUP, IDX_ADM_SYS_MENU)
);

insert into ADM_GROUP_PERMISSION (IDX_ADM_OPER_GROUP, IDX_ADM_SYS_MENU, PERMISSION) values (1, 1, 'C,R,U,D');