server:
  port: 8080
  servlet:
    session:
      cookie:
        name: APPSESSIONID

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

logging:
  level:
    root: warn
    org.springframework:
      web: warn
      security: info
      boot: info
    org.hibernate:
      SQL: warn
    com.authorization: debug


