server:
  port: 8100

spring:
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2

  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    show-sql: true

    hibernate:
      ddl-auto: validate


