spring:
  profiles:
    active: mysql
---
spring:
  config:
    activate:
      on-profile: mysql
  batch:
    job:
      names: ${job.name:NONE}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch
    username: minhyuk
    password: Xmfkdlvotm123$
  jpa:
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate

---

spring:
  config:
    activate:
      on-profile: h2
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  # JPA Config
  jpa:
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
