spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: minhyuk.yoo
    password: Xmfkdlvotm123$
    virtual-host: dev-vhost
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true




